module.exports = {
  collectCoverageFrom: [
    'src/**/*.{js,jsx}',
    '!src/**/?(*.)types.{js,jsx}',
    '!src/**/?(*.)helpers.{js,jsx}',
    '!src/**/?(*.)stories.{js,jsx}',
    '!src/**/?(*.)labs.{js,jsx}',
    '!src/**/?(*.)hsappstories.{js,jsx}',
    '!src/**/?(*.)storiesHelpers.{js,jsx}',
    '!src/**/stories/*.{js,jsx}',
    '!src/**/?(*.)testHelpers.{js,jsx}',
    '!src/tests/helpers/**/*.{js,jsx}',
    '!src/styles/tests/helpers/**/*.{js,jsx}',
    '!src/**/?(*.)css.{js,jsx}',
    '!src/index.{js,jsx}',
    '!src/components/Input/utils.{js,jsx}',
    '!src/components/Dropdown/Dropdown.Renderer.jsx',
    '!src/components/Dropdown/Dropdown.renderUtils.js',
    '!src/components/Popper/**/*.{js,jsx}',
    '!src/components/Route/**/*.{js,jsx}',
    '!src/utilities/browser.{js,jsx}',
    '!src/utilities/storybook.{js,jsx}',
    '!src/utilities/specs/**/*.{js,jsx}',
    '!src/utilities/env.{js,jsx}',
    '!src/utilities/react-router/**/*.{js,jsx}',
    '!src/utilities/smoothScroll.{js,jsx}',
    '!src/utilities/closest.js',
    '!src/utilities/node.js',
    '!src/utilities/component.js',
    '!src/utilities/memoizeOne.js',
    '!src/utilities/index.{js,jsx}',
    '!src/utilities/log.{js,jsx}',
    '!src/styles/includePaths.js',
    '!src/polyfills/**/*.{js,jsx}',
    '!src/vendors/**/*.{js,jsx}',
    '!src/components/index.js',
    '!src/components/Animate/animations/**/*',
    '!src/components/HSDS/**/*',
    '!src/components/ScopeProvider/**/*',
  ],
  coverageDirectory: 'coverage/',
  coverageThreshold: {
    global: {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
  },
  setupFiles: [
    '<rootDir>/config/polyfills.js',
    '<rootDir>/config/jsdomPolyfills.js',
  ],
  setupFilesAfterEnv: ['<rootDir>/config/jest/setupTests.js'],
  testMatch: [
    '<rootDir>/src/**/__tests__/**/*.test.(js|jsx)',
    '<rootDir>/src/**/?(*.)(spec|test).js?(x)',
  ],
  testEnvironment: 'node',
  testURL: 'http://localhost',
  transform: {
    '^.+\\.[t|j]sx?$': 'babel-jest',
    '^.+\\.css$': '<rootDir>/config/jest/cssTransform.js',
    '^(?!.*\\.(js|jsx|css|json)$)': '<rootDir>/config/jest/fileTransform.js',
  },
  transformIgnorePatterns: ['[/\\\\]node_modules[/\\\\].+\\.(js|jsx)$'],
  moduleFileExtensions: ['web.js', 'js', 'json', 'web.jsx', 'jsx'],
  watchPlugins: [
    'jest-watch-typeahead/filename',
    'jest-watch-typeahead/testname',
  ],
}
