module.exports = {
  collectCoverageFrom: [
    'src/**/*.{js,jsx,ts,tsx}',
    '!src/**/?(*.)types.{js,jsx}',
    '!src/**/?(*.)helpers.{js,jsx}',
    '!src/**/?(*.)testHelpers.{js,jsx,ts,tsx}',
    '!src/styles/tests/helpers/**/*.{js,jsx}',
    '!src/**/?(*.)css.{js,jsx}',
    '!src/index.{js,jsx}',
    '!src/components/Input/utils.{js,jsx}',
    '!src/components/Popper/**/*.{js,jsx}',
    '!src/tests/helpers/**/*.{js,jsx}',
    '!src/utilities/browser.{js,jsx,ts}',
    '!src/utilities/react-router/**/*.{js,jsx}',
    '!src/utilities/smoothScroll.{js,jsx}',
    '!src/utilities/closest.ts',
    '!src/utilities/index.{js,jsx}',
    '!src/utilities/log.{js,jsx}',
    '!src/styles/includePaths.js',
    '!src/polyfills/**/*.{js,jsx}',
    '!src/vendors/**/*.{js,jsx}',
    '!src/components/index.js',
    '!src/components/Animate/animations/**/*.js',
  ],
  coverageDirectory: 'coverage/',
  setupFiles: [
    '<rootDir>/config/polyfills.js',
    '<rootDir>/config/jsdomPolyfills.js',
  ],
  setupTestFrameworkScriptFile: '<rootDir>/config/jest/setupTests.js',
  testMatch: [
    '<rootDir>/src/**/__tests__/**/*.test.(js|jsx|ts|tsx)',
    '<rootDir>/src/**/?(*.)(spec|test).js?(x)',
    '<rootDir>/src/**/?(*.)(spec|test).ts?(x)',
  ],
  testEnvironment: 'node',
  testURL: 'http://localhost',
  transform: {
    '^.+\\.(js|jsx)$': '<rootDir>/node_modules/babel-jest',
    '^.+\\.(ts|tsx)$': 'ts-jest',
    '^.+\\.css$': '<rootDir>/config/jest/cssTransform.js',
    '^(?!.*\\.(js|jsx|css|json)$)': '<rootDir>/config/jest/fileTransform.js',
  },
  transformIgnorePatterns: ['[/\\\\]node_modules[/\\\\].+\\.(js|jsx)$'],
  moduleNameMapper: {
    '^react-native$': 'react-native-web',
  },
  moduleFileExtensions: ['web.js', 'js', 'json', 'web.jsx', 'jsx', 'ts', 'tsx'],
  watchPlugins: [
    'jest-watch-typeahead/filename',
    'jest-watch-typeahead/testname',
  ],
}
