export const emojiSet = [
  {
    colons: ':unicorn_face:',
    hoverBackgroundColor: 'purple',
    name: 'Unicorn Face',
    symbol: '🦄',
    unified: '1f984',
    value: 'Unicorn Face',
  },
  {
    colons: ':heart:',
    hoverBackgroundColor: 'red',
    name: 'Heavy Black Heart',
    symbol: '❤️',
    unified: '2764-fe0f',
    value: 'Heavy Black Heart',
  },
  {
    colons: ':slightly_smiling_face:',
    hoverBackgroundColor: 'grey',
    name: 'Slightly Smiling Face',
    symbol: '🙂',
    unified: '1f642',
    value: 'Slightly Smiling Face',
  },
  {
    colons: ':slightly_frowning_face:',
    hoverBackgroundColor: 'yellow',
    name: 'Slightly Frowning Face',
    symbol: '🙁',
    unified: '1f641',
    value: 'Slightly Frowning Face',
  },
  {
    colons: ':+1:',
    hoverBackgroundColor: 'yellow',
    name: 'Thumbs Up Sign',
    symbol: '👍',
    unified: '1f44d',
    value: 'Thumbs Up Sign',
  },
  {
    colons: ':-1:',
    hoverBackgroundColor: 'yellow',
    name: 'Thumbs Down Sign',
    symbol: '👎',
    unified: '1f44e',
    value: 'Thumbs Down Sign',
  },
]
