import React from 'react'

export const COMPONENT_KEY = 'Icon'

// List of available icons
export const ICONS = {
  activity: true,
  alert: true,
  'align-center': true,
  'align-left': true,
  'align-right': true,
  'animals-and-nature': true,
  'arrow-down-huge': true,
  'arrow-left': true,
  'arrow-left-double-large': true,
  'arrow-left-single-large': true,
  'arrow-left-small': true,
  'arrow-merge': true,
  'arrow-right': true,
  'arrow-right-double-large': true,
  'arrow-right-single-large': true,
  'arrow-right-small': true,
  'arrow-swerve': true,
  'arrow-two-way': true,
  'arrow-up-huge': true,
  assign: true,
  assigned: true,
  at: true,
  attach: true,
  'attach-large': true,
  'attach-small': true,
  attachment: true,
  bcc: true,
  bell: true,
  'bell-small': true,
  bin: true,
  bold: true,
  'bubble-dots': true,
  'bubble-dots-duplicate': true,
  'bubble-dots-plus': true,
  'bubble-tick': true,
  buoy: true,
  calendar: true,
  call: true,
  'call-large': true,
  camera: true,
  'caret-down': true,
  'caret-left': true,
  'caret-right': true,
  'caret-up': true,
  chat: true,
  'chat-active': true,
  'chat-small': true,
  'chat-square': true,
  check: true,
  'checkbox-large': true,
  'checkbox-small': true,
  'circle-arrow-down': true,
  'circle-arrow-left': true,
  'circle-arrow-right': true,
  'circle-arrow-up': true,
  'circle-cross': true,
  'circle-minus': true,
  'circle-plus': true,
  'circle-tick': true,
  clock: true,
  'clock-large': true,
  'clock-small': true,
  clockLarge: true,
  closed: true,
  cloud: true,
  cog: true,
  collapse: true,
  compose: true,
  connection: true,
  copy: true,
  'cross-large': true,
  'cross-medium': true,
  'cross-medium-alt': true,
  'cross-small': true,
  crossLarge: true,
  cursor: true,
  dashboard: true,
  document: true,
  'document-in': true,
  'document-out': true,
  dollar: true,
  drafts: true,
  drag: true,
  'drag-handle': true,
  duplicate: true,
  ellipsis: true,
  'ellipsis-small': true,
  emoji: true,
  envelope: true,
  'envelope-large': true,
  'envelope-open': true,
  eye: true,
  'eye-closed': true,
  'fab-antenna': true,
  'fab-buoy': true,
  'fab-chat': true,
  'fab-question': true,
  'fab-search': true,
  fields: true,
  flags: true,
  folder: true,
  'folder-check': true,
  'folder-open': true,
  'folder-open-small': true,
  'food-and-drink': true,
  forward: true,
  fullscreen: true,
  globe: true,
  graph: true,
  heart: true,
  'helpscout-logo': true,
  house: true,
  'hs-logo': true,
  hyphen: true,
  image: true,
  'image-add': true,
  'image-large': true,
  'image-plus': true,
  inbox: true,
  info: true,
  information: true,
  italic: true,
  kebab: true,
  key: true,
  keyboard: true,
  'large-double-arrow-left': true,
  'large-double-arrow-right': true,
  'large-single-arrow-left': true,
  'large-single-arrow-right': true,
  link: true,
  list: true,
  'lock-closed': true,
  'lock-open': true,
  magazine: true,
  markup: true,
  meatball: true,
  'menu-small': true,
  mine: true,
  minimize: true,
  minus: true,
  moon: true,
  'new-convo': true,
  'new-window': true,
  'new-window-large': true,
  note: true,
  objects: true,
  offline: true,
  'option-dots': true,
  'paper-plane': true,
  pause: true,
  'pencil-small': true,
  period: true,
  'person-multiple': true,
  'person-plus': true,
  'person-tick': true,
  'person-x': true,
  'play-video': true,
  plus: true,
  'plus-large': true,
  'plus-medium': true,
  'plus-small': true,
  power: true,
  printer: true,
  quote: true,
  'record-video': true,
  refresh: true,
  reply: true,
  rosette: true,
  screen: true,
  search: true,
  'search-medium': true,
  'search-small': true,
  'shopping-cart': true,
  sign: true,
  'small-paperclip': true,
  'social-facebook': true,
  'social-twitter': true,
  spam: true,
  spinner: true,
  star: true,
  'star-small': true,
  status: true,
  stop: true,
  suitcase: true,
  symbols: true,
  table: true,
  tag: true,
  text: true,
  tick: true,
  'tick-large': true,
  'tick-small': true,
  toggle: true,
  trash: true,
  'travel-and-places': true,
  'tray-large': true,
  'tray-small': true,
  'tray-success': true,
  trophy: true,
  unassigned: true,
  underline: true,
  user: true,
  'user-x': true,
  workflow: true,
  'workflow-small': true,
  'x-large-single-arrow-left': true,
  'x-large-single-arrow-right': true,
}

export default ICONS

export const ALIASES = {
  'arrow-left-double-large': 'large-double-arrow-left',
  'arrow-left-single-large': 'large-single-arrow-left',
  'arrow-right-double-large': 'large-double-arrow-right',
  'arrow-right-single-large': 'large-single-arrow-right',
  clockLarge: 'clock-large',
  crossLarge: 'cross-large',
  checkmark: 'check',
  'option-dots': 'meatball',
  plus: 'plus-large',
  plusLarge: 'plus-large',
  tick: 'tick-large',
}

export const getIconComponent = name => {
  if (!name) return null

  const iconName = ALIASES[name] || name
  // Only attempt to retrieve supported icons
  if (!ICONS[iconName]) return null

  const IconComponent = require(`../Icons/${iconName}`).default

  return IconComponent ? React.createElement(IconComponent) : null
}

export const renameSVGIds = (svgHtml, name) => {
  if (!svgHtml) {
    return svgHtml
  }
  const regexHash = new RegExp(`\#${name}`, 'gi')
  const regexQuote = new RegExp(`\"${name}`, 'gi')
  return svgHtml
    .replace(regexHash, `#hsds-icons-${name}`)
    .replace(regexQuote, `"hsds-icons-${name}`)
}
