import { injectGlobal } from '../src/components/styled'
import '../src/styles/blue.scss'
// import '../src/styles/blue.hs-app.scss'

import './Alert'
import './AnimateGroup'
import './Animate'
import './Attachment'
import './AttachmentList'
import './Avatar'
import './AvatarGrid'
import './AvatarList'
import './AvatarStack'
import './Badge'
import './Button'
import './Card'
import './ChatInbox'
import './ChatList'
import './ChatSidebar'
import './ChatScroller'
import './ChatTranscript'
import './Checkbox'
import './Code'
import './Collapsible'
import './CloseButton'
import './DetailList'
import './Dropdown'
import './EmbedChat'
import './Emoji'
import './EmojiPicker'
import './Emoticon'
import './Fancy/index'
import './Flexy'
import './Grid'
import './Heading'
import './Huzzah'
import './Icon'
import './Illo'
import './Image'
import './InfiniteScroller'
import './Input'
import './Message'
import './Modal'
import './Notification'
import './NotificationStack'
import './Link'
import './List'
import './LoadingDots'
import './Overlay'
import './Overflow'
import './Page'
import './ProgressBar'
import './Radio'
import './Samp'
import './ScrollLock'
import './Scrollable'
import './Select'
import './SidebarCollapsibleCard'
import './Skeleton'
import './Sortable'
import './Spinner'
import './StatusAvatar'
import './StatusBadge'
import './StatusBar'
import './StatusDot'
import './Switch'
import './Tag'
import './TagList'
import './Text'
import './Timeline'
import './Timestamp'
import './Toolbar'
import './Tooltip'
import './Truncate'
import './VisuallyHidden'

import './Color'

injectGlobal`
  html, body {
    margin: 0;
    padding: 0;
  }
`
